apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: pfe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pfe-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: rag-storage
              mountPath: /app/data
          envFrom:
            - secretRef:
                name: pfe-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/tc_hub_db"
            - name: ML_SERVICE_URL
              value: "http://ml-service:5000"
      volumes:
        - name: rag-storage
          persistentVolumeClaim:
            claimName: rag-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: pfe-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
