spring.application.name=TC-Project
spring.datasource.url=jdbc:postgresql://postgres-service:5432/tc_hub_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=TC-Hub-Secret-Key-Tunisie-Clearing-2024-XYZ-SuperSecure
app.jwt.expiration-ms=86400000
server.port=8082
spring.web.cors.allowed-origins=http://localhost

# Cloudinary
cloudinary.cloud_name=djsak9yrz
cloudinary.api_key=658165742827392
cloudinary.api_secret=RN6VyfoXuIDIynVUVtKIDpD2T_U

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alabbr55@gmail.com
spring.mail.password=vazy tmql xfjn xnbh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
