spring.config.import=optional:file:.env.properties
spring.application.name=TC-Project

# =============================================
# DataSource — PostgreSQL
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/tc_hub_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / Hibernate
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =============================================
# JWT Configuration
# =============================================
app.jwt.secret=TC-Hub-Secret-Key-Tunisie-Clearing-2024-XYZ-SuperSecure
app.jwt.expiration-ms=86400000

# =============================================
# Server
# =============================================
server.port=8080

# =============================================
# CORS (autorise Angular en dev)
# =============================================
spring.web.cors.allowed-origins=http://localhost:4200

# Cloudinary
cloudinary.cloud_name=djsak9yrz
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alabbr55@gmail.com
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =============================================
# Multipart / File Upload
# =============================================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# =============================================
# Groq AI Configuration (Llama 3.3 70B)
# =============================================
groq.api.key=${GROQ_API_KEY}
groq.model.name=llama-3.3-70b-versatile

# Old Gemini key (backup)
# gemini.api.key=${GEMINI_API_KEY}

# LlamaParse
llamaparse.api.key=${LLAMAPARSE_API_KEY}
